//! Wallpaper color extraction → woven-theme.toml
//!
//! Extracts dominant colors from the current wallpaper using k-means clustering
//! and writes a theme file that woven-bar can watch and apply.

use std::io::Write;

/// Extract dominant colors from BGRA pixel data and write the theme file.
pub fn extract_and_write(bgra: &[u8], w: u32, h: u32) {
    let colors = extract_colors(bgra, w, h, 6);
    if colors.is_empty() { return; }

    let theme = pick_theme(&colors);
    if let Err(e) = write_theme(&theme) {
        tracing::warn!("theme: failed to write: {e}");
    } else {
        tracing::info!("theme: wrote wallpaper theme — bg={} fg={} accent={} dim={}",
            theme.background, theme.foreground, theme.accent, theme.dim);
    }
}

struct ThemeColors {
    background:        String,
    foreground:        String,
    accent:            String,
    dim:               String,
    bubble_background: String,
}

fn write_theme(theme: &ThemeColors) -> std::io::Result<()> {
    let runtime = std::env::var("XDG_RUNTIME_DIR").unwrap_or_else(|_| "/tmp".into());
    let path = format!("{runtime}/woven-theme.toml");
    let tmp  = format!("{path}.tmp");

    let content = format!(
        "# Auto-generated by woven-wall — wallpaper color extraction\n\
         background        = \"{}\"\n\
         foreground        = \"{}\"\n\
         accent            = \"{}\"\n\
         dim               = \"{}\"\n\
         bubble_background = \"{}\"\n\
         radius            = 7\n\
         font_size         = 13.0\n",
        theme.background, theme.foreground, theme.accent, theme.dim, theme.bubble_background,
    );

    let mut f = std::fs::File::create(&tmp)?;
    f.write_all(content.as_bytes())?;
    f.sync_all()?;
    std::fs::rename(&tmp, &path)?;
    Ok(())
}

// ── Color extraction via simplified k-means ─────────────────────────────────

#[derive(Clone, Copy)]
struct Lab { l: f32, a: f32, b: f32 }

#[derive(Clone, Copy)]
struct Rgb { r: u8, g: u8, b: u8 }

impl Rgb {
    fn to_lab(self) -> Lab {
        // sRGB → linear
        let rl = srgb_to_linear(self.r as f32 / 255.0);
        let gl = srgb_to_linear(self.g as f32 / 255.0);
        let bl = srgb_to_linear(self.b as f32 / 255.0);

        // linear RGB → XYZ (D65)
        let x = 0.4124564 * rl + 0.3575761 * gl + 0.1804375 * bl;
        let y = 0.2126729 * rl + 0.7151522 * gl + 0.0721750 * bl;
        let z = 0.0193339 * rl + 0.1191920 * gl + 0.9503041 * bl;

        // XYZ → Lab
        let xn = x / 0.95047;
        let yn = y / 1.00000;
        let zn = z / 1.08883;

        let fx = lab_f(xn);
        let fy = lab_f(yn);
        let fz = lab_f(zn);

        Lab {
            l: 116.0 * fy - 16.0,
            a: 500.0 * (fx - fy),
            b: 200.0 * (fy - fz),
        }
    }

    fn to_hex(self) -> String {
        format!("#{:02x}{:02x}{:02x}", self.r, self.g, self.b)
    }

    fn lightness(self) -> f32 {
        // perceptual luminance
        0.299 * self.r as f32 + 0.587 * self.g as f32 + 0.114 * self.b as f32
    }

    fn saturation(self) -> f32 {
        let r = self.r as f32 / 255.0;
        let g = self.g as f32 / 255.0;
        let b = self.b as f32 / 255.0;
        let max = r.max(g).max(b);
        let min = r.min(g).min(b);
        if max < 0.001 { return 0.0; }
        (max - min) / max
    }
}

fn srgb_to_linear(v: f32) -> f32 {
    if v <= 0.04045 { v / 12.92 } else { ((v + 0.055) / 1.055).powf(2.4) }
}

fn lab_f(t: f32) -> f32 {
    if t > 0.008856 { t.cbrt() } else { 7.787 * t + 16.0 / 116.0 }
}

fn lab_dist(a: &Lab, b: &Lab) -> f32 {
    let dl = a.l - b.l;
    let da = a.a - b.a;
    let db = a.b - b.b;
    (dl * dl + da * da + db * db).sqrt()
}

/// Downsample the BGRA image and run k-means to find k dominant colors.
fn extract_colors(bgra: &[u8], w: u32, h: u32, k: usize) -> Vec<Rgb> {
    // downsample to ~80x80 max
    let step = ((w.max(h)) / 80).max(1) as usize;
    let mut samples: Vec<Rgb> = Vec::with_capacity(6400);

    let mut py = 0u32;
    while py < h {
        let mut px = 0u32;
        while px < w {
            let off = ((py * w + px) * 4) as usize;
            if off + 3 < bgra.len() {
                samples.push(Rgb {
                    r: bgra[off + 2], // BGRA → R is at offset 2
                    g: bgra[off + 1],
                    b: bgra[off],
                });
            }
            px += step as u32;
        }
        py += step as u32;
    }

    if samples.is_empty() { return Vec::new(); }

    // convert to Lab for perceptually uniform clustering
    let labs: Vec<Lab> = samples.iter().map(|c| c.to_lab()).collect();

    // init centroids: spread across the sample space
    let mut centroids: Vec<Lab> = Vec::with_capacity(k);
    let chunk = samples.len() / k;
    for i in 0..k {
        centroids.push(labs[i * chunk]);
    }

    // k-means iterations
    let mut assignments = vec![0usize; samples.len()];
    for _ in 0..15 {
        // assign
        for (i, lab) in labs.iter().enumerate() {
            let mut best_d = f32::MAX;
            let mut best_c = 0;
            for (ci, centroid) in centroids.iter().enumerate() {
                let d = lab_dist(lab, centroid);
                if d < best_d { best_d = d; best_c = ci; }
            }
            assignments[i] = best_c;
        }

        // update centroids
        let mut sums = vec![(0.0f32, 0.0f32, 0.0f32, 0u32); k];
        for (i, lab) in labs.iter().enumerate() {
            let c = assignments[i];
            sums[c].0 += lab.l;
            sums[c].1 += lab.a;
            sums[c].2 += lab.b;
            sums[c].3 += 1;
        }
        for (ci, s) in sums.iter().enumerate() {
            if s.3 > 0 {
                centroids[ci] = Lab {
                    l: s.0 / s.3 as f32,
                    a: s.1 / s.3 as f32,
                    b: s.2 / s.3 as f32,
                };
            }
        }
    }

    // convert centroids back to RGB, weighted by cluster size
    let mut cluster_sizes = vec![0u32; k];
    let mut cluster_rgb_sum = vec![(0u64, 0u64, 0u64); k];
    for (i, sample) in samples.iter().enumerate() {
        let c = assignments[i];
        cluster_sizes[c] += 1;
        cluster_rgb_sum[c].0 += sample.r as u64;
        cluster_rgb_sum[c].1 += sample.g as u64;
        cluster_rgb_sum[c].2 += sample.b as u64;
    }

    let mut colors: Vec<(Rgb, u32)> = Vec::new();
    for i in 0..k {
        if cluster_sizes[i] == 0 { continue; }
        let n = cluster_sizes[i] as u64;
        colors.push((Rgb {
            r: (cluster_rgb_sum[i].0 / n) as u8,
            g: (cluster_rgb_sum[i].1 / n) as u8,
            b: (cluster_rgb_sum[i].2 / n) as u8,
        }, cluster_sizes[i]));
    }

    // sort by cluster size (most dominant first)
    colors.sort_by(|a, b| b.1.cmp(&a.1));
    colors.into_iter().map(|(c, _)| c).collect()
}

/// Pick background, foreground, accent, and dim from extracted palette.
fn pick_theme(colors: &[Rgb]) -> ThemeColors {
    // sort by lightness
    let mut by_light: Vec<(usize, f32)> = colors.iter().enumerate()
        .map(|(i, c)| (i, c.lightness()))
        .collect();
    by_light.sort_by(|a, b| a.1.partial_cmp(&b.1).unwrap());

    // background: darkest color, but darken it further for readability
    let bg_base = colors[by_light[0].0];
    let background = Rgb {
        r: (bg_base.r as f32 * 0.4) as u8,
        g: (bg_base.g as f32 * 0.4) as u8,
        b: (bg_base.b as f32 * 0.4) as u8,
    };

    // foreground: lightest color, but ensure it's bright enough
    let fg_base = colors[by_light.last().unwrap().0];
    let foreground = if fg_base.lightness() < 160.0 {
        // too dark for foreground — use a light tint of it
        Rgb {
            r: ((fg_base.r as f32 * 0.3) + 180.0).min(255.0) as u8,
            g: ((fg_base.g as f32 * 0.3) + 180.0).min(255.0) as u8,
            b: ((fg_base.b as f32 * 0.3) + 180.0).min(255.0) as u8,
        }
    } else {
        fg_base
    };

    // accent: most saturated color (excluding darkest/lightest)
    let mid_colors: Vec<(usize, f32)> = colors.iter().enumerate()
        .filter(|(i, _)| *i != by_light[0].0 && *i != by_light.last().unwrap().0)
        .map(|(i, c)| (i, c.saturation()))
        .collect();

    let accent_idx = mid_colors.iter()
        .max_by(|a, b| a.1.partial_cmp(&b.1).unwrap())
        .map(|(i, _)| *i)
        .unwrap_or(0);
    let accent = colors[accent_idx];

    // dim: midpoint between background and accent, desaturated
    let dim = Rgb {
        r: ((background.r as u16 + accent.r as u16) / 2) as u8,
        g: ((background.g as u16 + accent.g as u16) / 2) as u8,
        b: ((background.b as u16 + accent.b as u16) / 2) as u8,
    };

    // bubble background: slightly lighter than bar background with a hint of accent
    let bubble_bg = Rgb {
        r: (background.r as f32 * 0.6 + accent.r as f32 * 0.15 + 15.0).min(255.0) as u8,
        g: (background.g as f32 * 0.6 + accent.g as f32 * 0.15 + 10.0).min(255.0) as u8,
        b: (background.b as f32 * 0.6 + accent.b as f32 * 0.15 + 20.0).min(255.0) as u8,
    };

    ThemeColors {
        background:        background.to_hex(),
        foreground:        foreground.to_hex(),
        accent:            accent.to_hex(),
        dim:               dim.to_hex(),
        bubble_background: bubble_bg.to_hex(),
    }
}
